name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gocv/opencv
    steps:
      - uses: actions/checkout@v6
      - name: Test
        run: go test -v ./...
      - name: Build
        run: go build -v ./...
